# Generated by Django 3.0.5 on 2020-04-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='state',
            new_name='country',
        ),
    ]
