# Generated by Django 3.0.5 on 2020-04-25 10:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200425_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
